name: Build Deploy Invalidate

on:
    push:
        branches:
            - main

jobs:
    My-CI-CD-Jobs:
        runs-on: ubuntu-latest
        steps:
            - name: 아무거나 실행해보기
              run: echo "이히히히"
