name: Build Deploy Invalidate

on:
    push:
        branches:
            - main
# 할 것
# 1. 인증
# 2. s3 버킷 비우기
# 3. repo download
# 4. npm install
# 5. npm run build
# 6. dist 폴더 내용물 s3에 올리기
# 7. cloudfront invalidate cache

jobs:
    My-CI-CD-Jobs:
        runs-on: ubuntu-latest
        steps:
            # https://github.com/actions/checkout
            - name: 깃헙에서 레포 다운받기
              uses: actions/checkout@v5
            
            - name: 의존성 설치, 빌드
              run: |
                npm install
                npm run build
            
            # https://github.com/aws-actions/configure-aws-credentials
            # aws console에서 현재 지역을 확인할 수 있음
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@main # Or a specific version
              with:
                aws-region: ap-northeast-2
                aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
                aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            
            # -r이 안 됨. 같은 이유로 -rf 도 안 될 것
            # aws 명령어 쓸 땐 꼭 s3 써줘야 함 << 아주 중요`
            - name: S3 버켓에 있는 모든 파일 삭제
              run: aws s3 rm --recursive s3://aws-oz-assignment
            
            - name: dist 폴더 내용물 업로드
              run: aws s3 cp ./dist s3://aws-oz-assignment --recursive

            - name: CloudFront 캐시 무효화
              run: aws cloudFront create-invalidation --distribution-id E1KKUONDTQ982M --path "/*"
